"use client";

import { useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, BarChart3, Building2, CalendarCheck, Check, ChevronDown, Clock3, CreditCard, Headphones, HeartPulse, Languages, LineChart, MessageCircle, Phone, Send, ShieldCheck, Sparkles, Stethoscope, Store, Users, WandSparkles } from "lucide-react";

const fade = { hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0 } };
const pain = [
  [Phone, "The phone rings while you're busy", "You're with a patient. It rings. By evening that caller has booked somewhere else."],
  [Users, "The same five questions, all day", "“Timing enna?” “Fees evlo?” “Doctor irukkaara?” Your staff repeats it a hundred times."],
  [Clock3, "Nights and Sundays", "Your customers call when they're free — after 8pm, on holidays. Right now nobody picks up."],
  [LineChart, "You never find out", "A missed call leaves no trace. You don't know who called, or what they wanted."],
];
const flow = ["Customer calls", "Zeone picks up", "Talks in Tamil", "Answers their question", "Checks your calendar", "Books the appointment"];
const perks = [[Clock3,"Answers 24×7"],[Languages,"Real Tamil, not robotic"],[CalendarCheck,"Books appointments"],[ShieldCheck,"Never double-books"],[CreditCard,"Knows your fees & timings"],[Headphones,"Change or cancel on the call"],[Users,"Repeats the name before booking"],[MessageCircle,"Every call saved as text"]];
const faq = [
  ["Can it really speak Tamil?", "Yes — the way your customers actually talk, with English words mixed in. Not a translated robot voice."],
  ["What if it doesn't know the answer?", "It says so honestly and offers to arrange a call back. It will never invent a service you don't provide or a price you didn't set."],
  ["Can it book two people into the same slot?", "No. Before it confirms anything it checks your calendar, your working hours and your weekly off. If the slot is taken, it offers the next free one."],
  ["Do I need to change my phone number?", "No. Zeone is connected to the number your customers already call. Nothing changes for them."],
  ["Do I need any software or technical knowledge?", "None. You tell us your timings, services, fees and doctors. Every booking and every conversation appears in your Zeone dashboard."],
  ["Can I change my details later?", "Yes. Change a fee, add a service, mark a holiday — Zeone starts giving the new answer straight away."],
];

function Button({ children, light = false, href = "/start" }: { children: React.ReactNode; light?: boolean; href?: string }) { return <Link href={href} prefetch className={light ? "btn btn-light" : "btn"}>{children}<ArrowRight size={16}/></Link> }

export default function Home() {
  const [open, setOpen] = useState<number | null>(0);
  const [step, setStep] = useState(1);
  return <main>
    <nav className="nav"><a className="brand" href="#top"><span>Z</span>zeone</a><div className="nav-links"><a href="#how">How it works</a><a href="#setup">Product</a><a href="#industries">Who it's for</a></div><Link href="/start" prefetch className="nav-cta">Try Zeone free <ArrowRight size={15}/></Link></nav>

    <section id="top" className="hero section"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><motion.div initial="hidden" animate="show" transition={{staggerChildren:.12}} className="hero-copy"><motion.div variants={fade} className="eyebrow"><span className="pulse"/> Made for Tamil Nadu businesses</motion.div><motion.h1 variants={fade}>Never lose another customer because nobody picked up the <em>phone.</em></motion.h1><motion.p variants={fade}>Zeone answers every call in Tamil, tells your customers your timings, services and fees, and books their appointment — at 11 at night, on a Sunday, whenever they call.</motion.p><motion.div variants={fade} className="hero-actions"><Button>Try Zeone free</Button><button className="text-btn"><span className="play">▶</span> Hear a real call</button></motion.div><motion.div variants={fade} className="hero-proof"><div className="avatar-stack"><i>த</i><i>+</i><i>A</i></div><span>Tamil and English, the way your customers speak<br/><b>“இனி ஒரு call-உம் miss ஆகாது.”</b></span></motion.div></motion.div>
      <motion.div initial={{opacity:0,scale:.94,y:18}} animate={{opacity:1,scale:1,y:0}} transition={{duration:.7,delay:.25}} className="call-orbit"><div className="ring ring-1"/><div className="ring ring-2"/><div className="ring ring-3"/><div className="call-card"><div className="call-top"><div className="caller"><div className="caller-icon"><Phone size={18}/></div><div><b>Incoming call</b><small>+91 978•• ••320</small></div></div><span className="live">LIVE</span></div><div className="wave">{Array.from({length:24}).map((_,i)=><i key={i} style={{height:`${10 + ((i*13)%35)}px`}}/>)}</div><div className="transcript"><p><b>Customer</b> “நாளைக்கு appointment கிடைக்குமா?”</p><p className="zeone-line"><b>Zeone</b> “கண்டிப்பா சார். காலை 10 மணிக்கு slot இருக்கு.”</p></div><div className="call-bottom"><span><Clock3 size={14}/> 00:42</span><span>Booking confirmed <Check size={14}/></span></div></div><div className="floating-tag tag-one"><span className="mini-icon"><Languages size={14}/></span><div><b>Understood in Tamil</b><small>No menu, no “press 1”</small></div><Check size={15}/></div><div className="floating-tag tag-two"><span className="mini-icon green"><CalendarCheck size={14}/></span><div><b>Slot checked & booked</b><small>Tomorrow, 10:00 AM</small></div></div></motion.div>
    </section>

    <section className="section pain-section"><div className="section-label">THE COST OF A RINGING PHONE</div><h2>Every missed call is a customer<br/>walking into the next shop.</h2><div className="pain-grid">{pain.map(([Icon,title,text],i)=><motion.article initial="hidden" whileInView="show" viewport={{once:true}} transition={{delay:i*.08}} variants={fade} className="pain-card" key={title as string}><span className="icon-wrap"><Icon size={21}/></span><h3>{title as string}</h3><p>{text as string}</p><span className="card-index">0{i+1}</span></motion.article>)}</div></section>

    <section id="how" className="section how"><div className="section-label">ONE CALL. COMPLETELY HANDLED.</div><h2>You run your business.<br/><em>Zeone runs the front desk.</em></h2><div className="flow">{flow.map((item,i)=><div className="flow-step" key={item}><span>{String(i+1).padStart(2,"0")}</span><b>{item}</b>{i<flow.length-1&&<i className="flow-line"/>}</div>)}</div><div className="how-note"><Sparkles size={16}/><span>From “hello” to a confirmed appointment — nobody on your team has to touch the phone.</span></div></section>

    <section id="setup" className="section setup"><div className="setup-copy"><div className="section-label">SET UP WITH YOUR DETAILS</div><h2>It only says<br/><em>what you tell it.</em></h2><p>Your timings, your doctors, your services, your fees, your weekly off. Zeone answers from that — and nothing else. No training, no technical work, no AI knowledge needed.</p><div className="setup-points"><span><Check size={17}/> We set it up for you</span><span><Check size={17}/> Change anything, anytime</span></div></div><div className="wizard"><div className="wizard-top"><div><span>YOUR BUSINESS DETAILS</span><h3>Business details</h3></div><b>{step}/7</b></div><div className="stepper">{Array.from({length:7}).map((_,i)=><i onClick={()=>setStep(i+1)} className={i+1<=step?"active":""} key={i}/>)}</div><div className="wizard-form">{step===1 ? <><label>Business name<input defaultValue="Sri Clinic &amp; Diagnostic Centre"/></label><label>Business type<div className="select">Clinic <ChevronDown size={16}/></div></label><div className="ready-note"><Stethoscope size={17}/><span>We’ll set Zeone up for patient calls and appointments.</span></div></> : <div className="placeholder-step"><WandSparkles size={25}/><h4>{["Working hours & weekly off","Your doctors","Services & fees","Questions people always ask","Your rules (parking, card, home collection)","Check everything"][step-2]}</h4><p>Zeone answers only from what you enter here. That is why we go through it with you, line by line.</p></div>}</div><div className="wizard-bottom"><button className="back" onClick={()=>setStep(Math.max(1,step-1))}>Back</button><button className="continue" onClick={()=>setStep(step===7?1:step+1)}>{step===7?"Finish setup":"Continue"}<ArrowRight size={15}/></button></div></div></section>

    <section className="section conversation"><div className="conversation-copy"><div className="section-label">THE CALL THEY’LL REMEMBER</div><h2>It sounds like<br/><em>your best employee.</em></h2><p>Warm, quick and actually helpful. It understands “நாளைக்கு காலைல”, it repeats the caller’s name back before booking so your register is correct, and it can change or cancel an appointment on the same call.</p><div className="quote-mark">“</div><blockquote>“உங்க கிளினிக் பேசுற மாதிரியே, உங்க customer கிட்ட பேசும்.”<footer>— Tamil first. Not translated.</footer></blockquote></div><div className="phone-ui"><div className="phone-notch"/><div className="phone-head"><span>9:41</span><div className="phone-contact"><span className="z-avatar">Z</span><div><b>Zeone · Sri Clinic</b><small>Front desk</small></div></div><span>•••</span></div><div className="messages"><div className="bubble customer">நாளைக்கு appointment கிடைக்குமா?<small>9:40 AM</small></div><div className="bubble bot">கண்டிப்பா சார். எந்த டாக்டரை பாக்கணும்?<small>9:40 AM</small></div><div className="bubble customer">டாக்டர் ராஜேஷ்</div><div className="bubble bot">காலை 10 மணிக்கு slot இருக்கு. பேரு சொல்லுங்க சார்?<small>9:41 AM</small></div><div className="booked"><Check size={13}/> Appointment booked · Tomorrow, 10:00 AM</div></div><div className="message-input">Message <Send size={16}/></div></div></section>

    <section className="section dashboard"><div className="dash-heading"><div><div className="section-label">EVERYTHING, AT A GLANCE</div><h2>Your business is talking.<br/><em>Now you can listen.</em></h2></div><Button>See it with your business</Button></div><figure className="dash-window"><img className="dash-shot" src="/dash-today.webp" width={2000} height={1664} alt="The Zeone dashboard home screen for a clinic: 34 calls handled, 12 booked today, 22 upcoming appointments."/><figcaption>Your day, the moment you open it — how many called, how many booked, what&rsquo;s still coming.</figcaption></figure><div className="dash-grid">{[["/dash-appointments.webp",1500,1562,"Appointments","Every booking your phone made — who, what, when. No register, no missed entry.","Appointments screen listing bookings with customer name, service, doctor and time."],["/dash-conversations.webp",1500,1562,"Conversations","Open any call and read exactly what was said, in Tamil, word for word.","Conversations screen showing a full Tamil call transcript between a caller and the assistant."],["/dash-analytics.webp",1500,1346,"Analytics","Busiest hours, what callers asked for, and the enquiries you couldn’t serve.","Analytics screen with call volume, customer intent and peak hours charts."]].map(([src,w,h,title,note,alt])=><figure className="dash-card" key={title as string}><div className="dash-card-img"><img loading="lazy" src={src as string} width={w as number} height={h as number} alt={alt as string}/></div><figcaption><b>{title as string}</b><small>{note as string}</small></figcaption></figure>)}</div></section>

    <section className="section benefits"><div className="center-head"><div className="section-label">WHAT ZEONE ACTUALLY DOES</div><h2>Small changes. <em>Remarkable days.</em></h2></div><div className="perk-grid">{perks.map(([I,t])=>{const Icon=I as typeof Clock3;return <div className="perk" key={t as string}><span><Icon size={19}/></span>{t as string}<ArrowRight size={15}/></div>})}</div><div className="soon"><span className="soon-label">COMING SOON</span><div className="soon-grid"><div className="soon-item"><span><MessageCircle size={18}/></span><div><b>WhatsApp reminders</b><small>A reminder to the customer the day before their appointment, so fewer people forget to turn up.</small></div></div><div className="soon-item"><span><BarChart3 size={18}/></span><div><b>Call analytics</b><small>What customers asked for most this week, which days are busiest, and the enquiries you couldn’t serve.</small></div></div></div></div></section>

    <section id="industries" className="section industries"><div><div className="section-label">STARTING WITH CLINICS</div><h2>Built first for<br/><em>Tamil Nadu clinics.</em></h2></div><div className="industry-grid">{[[Stethoscope,"Clinics","Appointments, fees, doctor timings."],[Building2,"Diagnostic centres","Test charges, report timing, free slots."],[HeartPulse,"Dental & speciality","Every patient call answered."],[Sparkles,"Salons & spas","Coming next — the same front desk."],[WandSparkles,"Service centres","Coming next — enquiries handled."],[Store,"Shops & showrooms","Coming next — stock and timing calls."]].map(([I,t,d])=>{const Icon=I as typeof HeartPulse;return <article key={t as string}><span><Icon size={25}/></span><h3>{t as string}</h3><p>{d as string}</p><ArrowRight size={17}/></article>})}</div></section>

    <section className="section roi"><div className="roi-card"><div><div className="section-label">THE DIFFERENCE IS REAL</div><h2>Less ringing.<br/><em>More growing.</em></h2><p>Nothing about your day changes — except that the phone stops being a problem.</p></div><div className="roi-stats"><div className="before"><small>TODAY</small><p>Phone rings, <b>nobody free</b></p><p>After 8pm, <b>no answer</b></p><p>Bookings <b>on paper</b></p></div><div className="after"><small>WITH ZEONE <Check size={13}/></small><p><b>Every call</b> answered</p><p>Answers <b>at 11pm too</b></p><p>Bookings <b>in one place</b></p></div></div></div></section>

    <section className="section faq"><div className="center-head"><div className="section-label">GOOD QUESTIONS</div><h2>Everything you’re<br/><em>wondering about.</em></h2></div><div className="faq-list">{faq.map(([q,a],i)=><div className={open===i?"faq-item open":"faq-item"} key={q}><button onClick={()=>setOpen(open===i?null:i)}>{q as string}<span>{open===i?"−":"+"}</span></button>{open===i&&<p>{a as string}</p>}</div>)}</div></section>

    <section className="final"><div className="final-glow"/><span className="final-star">✦</span><div className="section-label">YOUR NEXT CUSTOMER IS CALLING</div><h2>Ready to never miss<br/>another customer?</h2><p>Give us 20 minutes. We’ll set Zeone up with your details and let you hear it answer a call.</p><div><Button light>Try Zeone free</Button><button className="final-demo">Talk to us <ArrowRight size={16}/></button></div><small>Free demo · We set it up for you · No technical work</small></section>
    <footer><a className="brand" href="#top"><span>Z</span>zeone</a><p>© 2026 Zeone. Made in Tamil Nadu, for Tamil Nadu businesses.</p><div><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Contact</a></div></footer>
  </main>;
}
